# Generated by Django 3.1.3 on 2021-03-25 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audiofield', '0002_auto_20180121_0750'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audiofile',
            options={'permissions': (('can_view_audiofile', 'can see Audio Files'),), 'verbose_name': 'audio file', 'verbose_name_plural': 'audio files'},
        ),
    ]
