# Generated by Django 4.1.7 on 2023-04-16 06:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("audiofield", "0003_auto_20210325_1230"),
        ("audiofield", "0003_auto_20220520_1655"),
    ]

    operations = []
