# Generated by Django 4.1.7 on 2023-04-19 08:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audiofield", "0004_merge_0003_auto_20210325_1230_0003_auto_20220520_1655"),
    ]

    operations = [
        migrations.AlterField(
            model_name="audiofile",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
